/*
 * TrianguloFractalView.java
 */

package com.rafaelsales.triangulofractal;

import com.rafaelsales.triangulofractal.fractal.Atrator;
import com.rafaelsales.triangulofractal.fractal.FractalGenerator;
import java.awt.Canvas;
import java.awt.Dimension;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JProgressBar;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class TrianguloFractalView extends FrameView implements ComponentListener {

    private FractalGenerator fractalGen;
    
    public TrianguloFractalView(SingleFrameApplication app) {
        super(app);
        
        this.getFrame().setMinimumSize(new Dimension(480, 480));
        
        initComponents();
        
        progresso.setMaximum(100);
        progresso.setMinimum(0);
        //Adiciona as cores na combo:
        for(int i = 0; i < FractalGenerator.Cor.values().length; i++) {
            listCor.addItem(FractalGenerator.Cor.values()[i]);
        }
        //Adiciona as formas:
        listForma.addItem(Atrator.Forma.values()[0]);
        listForma.addItem(Atrator.Forma.values()[1]);
        
        getFrame().addComponentListener(this);
        
        iniciarFractarGenerator();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = TrianguloFractalApp.getApplication().getMainFrame();
            aboutBox = new TrianguloFractalAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        TrianguloFractalApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        canvas = new java.awt.Canvas();
        panelAtrator = new javax.swing.JPanel();
        btCriar = new javax.swing.JButton();
        txtAtuacao = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        chkMovel = new javax.swing.JCheckBox();
        listForma = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btExcluirTodos = new javax.swing.JButton();
        panelFractal = new javax.swing.JPanel();
        btGerar = new javax.swing.JButton();
        progresso = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        listCor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtNumPontos = new javax.swing.JTextField();
        btCriarReferencia = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        btMenuLimparImagem = new javax.swing.JMenuItem();
        btMenuReiniciar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setMinimumSize(new java.awt.Dimension(480, 480));
        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.rafaelsales.triangulofractal.TrianguloFractalApp.class).getContext().getResourceMap(TrianguloFractalView.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        canvas.setBackground(resourceMap.getColor("canvas.background")); // NOI18N
        canvas.setName("canvas"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        panelAtrator.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelAtrator.border.title"))); // NOI18N
        panelAtrator.setName("panelAtrator"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.rafaelsales.triangulofractal.TrianguloFractalApp.class).getContext().getActionMap(TrianguloFractalView.class, this);
        btCriar.setAction(actionMap.get("criarAtrator")); // NOI18N
        btCriar.setText(resourceMap.getString("btCriar.text")); // NOI18N
        btCriar.setName("btCriar"); // NOI18N

        txtAtuacao.setModel(new javax.swing.SpinnerNumberModel(100, 20, 100, 20));
        txtAtuacao.setName("inputAtuacao"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        chkMovel.setText(resourceMap.getString("checkMovel.text")); // NOI18N
        chkMovel.setName("checkMovel"); // NOI18N

        listForma.setAction(actionMap.get("alterouForma")); // NOI18N
        listForma.setName("listForma"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtTamanho.setModel(new javax.swing.SpinnerNumberModel(20, 5, 100, 5));
        txtTamanho.setName("inputRaio"); // NOI18N
        txtTamanho.setVerifyInputWhenFocusTarget(false);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        btExcluirTodos.setAction(actionMap.get("excluirAtratores")); // NOI18N
        btExcluirTodos.setName("btExcluirTodos"); // NOI18N

        javax.swing.GroupLayout panelAtratorLayout = new javax.swing.GroupLayout(panelAtrator);
        panelAtrator.setLayout(panelAtratorLayout);
        panelAtratorLayout.setHorizontalGroup(
            panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtratorLayout.createSequentialGroup()
                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtratorLayout.createSequentialGroup()
                        .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAtratorLayout.createSequentialGroup()
                                .addComponent(txtAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(panelAtratorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelAtratorLayout.createSequentialGroup()
                                        .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))))))
                    .addGroup(panelAtratorLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtratorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chkMovel))
                    .addGroup(panelAtratorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btCriar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btExcluirTodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelAtratorLayout.setVerticalGroup(
            panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtratorLayout.createSequentialGroup()
                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkMovel)
                    .addComponent(listForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btExcluirTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAtratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btCriar)))
        );

        panelFractal.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelFractal.border.title"))); // NOI18N
        panelFractal.setName("panelFractal"); // NOI18N

        btGerar.setAction(actionMap.get("gerarFractal")); // NOI18N
        btGerar.setText(resourceMap.getString("btGerar.text")); // NOI18N
        btGerar.setName("btGerar"); // NOI18N

        progresso.setName("progresso"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        listCor.setName("listCor"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtNumPontos.setText(resourceMap.getString("txtNumPontos.text")); // NOI18N
        txtNumPontos.setName("txtNumPontos"); // NOI18N

        btCriarReferencia.setAction(actionMap.get("criarPontoReferencia")); // NOI18N
        btCriarReferencia.setText(resourceMap.getString("btCriarReferencia.text")); // NOI18N
        btCriarReferencia.setName("btCriarReferencia"); // NOI18N

        javax.swing.GroupLayout panelFractalLayout = new javax.swing.GroupLayout(panelFractal);
        panelFractal.setLayout(panelFractalLayout);
        panelFractalLayout.setHorizontalGroup(
            panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFractalLayout.createSequentialGroup()
                .addGroup(panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFractalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFractalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(listCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFractalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(progresso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCriarReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btGerar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFractalLayout.setVerticalGroup(
            panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFractalLayout.createSequentialGroup()
                .addGroup(panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCriarReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerar))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(panelAtrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFractal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAtrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFractal, 0, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        btMenuLimparImagem.setAction(actionMap.get("btMenuLimparImagem")); // NOI18N
        btMenuLimparImagem.setText(resourceMap.getString("btMenuLimparImagem.text")); // NOI18N
        btMenuLimparImagem.setName("btMenuLimparImagem"); // NOI18N
        fileMenu.add(btMenuLimparImagem);

        btMenuReiniciar.setAction(actionMap.get("btMenuReiniciar")); // NOI18N
        btMenuReiniciar.setText(resourceMap.getString("reiniciarMenu.text")); // NOI18N
        btMenuReiniciar.setName("reiniciarMenu"); // NOI18N
        fileMenu.add(btMenuReiniciar);

        jSeparator1.setName("jSeparator1"); // NOI18N
        fileMenu.add(jSeparator1);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btCriarReferencia;
    private javax.swing.JButton btExcluirTodos;
    private javax.swing.JButton btGerar;
    private javax.swing.JMenuItem btMenuLimparImagem;
    private javax.swing.JMenuItem btMenuReiniciar;
    private java.awt.Canvas canvas;
    private javax.swing.JCheckBox chkMovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox listCor;
    private javax.swing.JComboBox listForma;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelAtrator;
    private javax.swing.JPanel panelFractal;
    private javax.swing.JProgressBar progresso;
    private javax.swing.JSpinner txtAtuacao;
    private javax.swing.JTextField txtNumPontos;
    private javax.swing.JSpinner txtTamanho;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;

    public Canvas getCanvas() {
        return canvas;
    }

    public JCheckBox getChkMovel() {
        return chkMovel;
    }

    public JComboBox getListCor() {
        return listCor;
    }

    public JComboBox getListForma() {
        return listForma;
    }

    public JProgressBar getProgresso() {
        return progresso;
    }

    public JSpinner getTxtAtuacao() {
        return txtAtuacao;
    }

    public JTextField getTxtNumPontos() {
        return txtNumPontos;
    }

    public JSpinner getTxtTamanho() {
        return txtTamanho;
    }

    @Action
    public void alterouForma() {
        Atrator.Forma forma = (Atrator.Forma)this.listForma.getSelectedItem();
        // Se a forma for um Ponto
        if (forma == Atrator.Forma.Ponto) {
            //chkMovel.setEnabled(true);
            txtTamanho.setEnabled(false);
        } else {//Se for Círculo ou Quadrado:
            //chkMovel.setEnabled(false);
            txtTamanho.setEnabled(true);
        }
    }
    
    @Action
    public void criarAtrator() {      
        boolean movel = chkMovel.isSelected();
        int atuacao, tamanho;
        try {
            atuacao = (Integer)txtAtuacao.getValue();
            tamanho = (Integer)txtTamanho.getValue();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(mainPanel, "Preencha os campos corretamente!", getFrame().getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        Atrator.Forma forma = (Atrator.Forma)listForma.getSelectedItem();
        fractalGen.criarAtrator(forma, movel, atuacao, tamanho);
    }
    
    @Action
    public void excluirAtratores() {
        fractalGen.getAtratores().clear();
        fractalGen.render();
    }

    @Action
    public void btMenuReiniciar() {
        iniciarFractarGenerator();
    }
    
    @Action
    public void btMenuLimparImagem() {
        fractalGen.limparImagem();
    }
    
    @Action
    public void criarPontoReferencia() {
        fractalGen.criarReferencia();
    }
   
    @Action
    public void gerarFractal() {
        if (fractalGen.getAtratores().size() < 3) {
            JOptionPane.showMessageDialog(mainPanel, "Você deve criar 3 atratores!", getFrame().getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        int numPontos;
        try {
            numPontos = Integer.parseInt(txtNumPontos.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(mainPanel, "Número de pontos inválido.", getFrame().getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!fractalGen.isReferenciaCriada()) {
            JOptionPane.showMessageDialog(mainPanel, "Você deve criar um ponto aleatório.", getFrame().getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        if (numPontos < 1000 || numPontos > 99999999) {
            JOptionPane.showMessageDialog(mainPanel, "O número de pontos deve ser maior que 1000 e menor que 99.999.999", getFrame().getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        FractalGenerator.Cor cor = (FractalGenerator.Cor)listCor.getSelectedItem();
        fractalGen.gerarFractal(numPontos, cor);
    }

    public void iniciarFractarGenerator() {
        if (fractalGen != null)
            fractalGen.finalizar();
        fractalGen = new FractalGenerator(this);
    }
    
    public void ativarBotoes(boolean ativar) {
        btGerar.setEnabled(ativar);
        btCriar.setEnabled(ativar);
        btExcluirTodos.setEnabled(ativar);
        btMenuReiniciar.setEnabled(ativar);
        btCriarReferencia.setEnabled(ativar);
        btMenuLimparImagem.setEnabled(ativar);
    }
            
    //==== EVENTOS

    public void componentResized(ComponentEvent e) {
    }

    public void componentMoved(ComponentEvent e) {
    }

    public void componentShown(ComponentEvent e) {
    }

    public void componentHidden(ComponentEvent e) {
    }


}
